export { OllamaClientError, OllamaHttpError, OllamaLoopbackClient } from "./client.ts";
export {
  catalogVariantHaystack,
  refreshOfficialCatalog,
  filterCatalogVariants,
  type CatalogFilter,
  type CatalogRefreshOptions,
  type CatalogRefreshResult,
  type OfficialCatalogCache,
  type OfficialCatalogModel,
  type OfficialCatalogSnapshot,
  type OfficialCatalogVariant,
} from "./catalog.ts";
export {
  OllamaHardwareEvidenceSource,
  OllamaPrivilegedBridgeAdapter,
  type OllamaInstallationProbe,
  type PlatformHardwareReader,
} from "./bridge.ts";
export {
  LocalOllamaSuiteController,
  type FolderPicker,
  type HardwareEvidenceSource,
  type LocalOllamaBridge,
  type LocalOllamaSuiteControllerOptions,
  type ObservablePullQueueStore,
  type RuntimeProbe,
} from "./controller.ts";
export {
  LocalChatManager,
  DEFAULT_CHAT_LIMITS,
  type ChatAttachment,
  type ChatHistoryStore,
  type ChatLimits,
  type ChatRole,
  type ChatStreamChunk,
  type ChatSubmission,
  type LocalChatGateway,
  type LocalChatMessage,
  type LocalChatSession,
} from "./chat.ts";
export {
  assessHardwareFit,
  type HardwareEvidence,
  type HardwareFitAssessment,
  type HardwareFitVerdict,
  type ModelFitEvidence,
} from "./hardware-fit.ts";
export {
  AllowlistedHarnessManager,
  PREBUILT_HARNESS_PROFILES,
  type HarnessLaunchPreview,
  type HarnessLaunchSelection,
  type HarnessProfile,
  type HarnessRuntime,
  type HarnessSnapshot,
  type HarnessSnapshotStore,
  type ResolvedExecutable,
} from "./harness.ts";
export {
  PersistentPullQueue,
  PULL_STORAGE_HEADROOM,
  requiredFreeBytesFor,
  type PullGateway,
  type PullProgress,
  type PullQueueItem,
  type PullQueueItemState,
  type PullQueueOptions,
  type PullQueueStore,
  type PullQueueSummary,
  type StoragePreflight,
} from "./pull-queue.ts";
export {
  CART_DISCLOSURE,
  LOCAL_OLLAMA_TABS,
  MODEL_DELETION_GATE,
  RUNTIME_HEALTH_VALUES,
  SEARCH_SCOPES,
  applyRecovery,
  cartShortfallBytes,
  formatBytes,
  runtimeSummary,
  searchStateFor,
  searchStatusFor,
  type CartViewState,
  type CatalogFacetValues,
  type CatalogViewState,
  type ChatTranscriptEntry,
  type ChatViewState,
  type ExecutableDetectionState,
  type GuidedRecovery,
  type HarnessSnapshotSummary,
  type HarnessViewState,
  type LocalOllamaSuiteActions,
  type LocalOllamaSuiteState,
  type LocalOllamaTab,
  type LocalOllamaTabDescriptor,
  type LocalRuntimeModel,
  type PreviewHarnessInput,
  type RecoveryActionId,
  type RuntimeHealth,
  type RuntimeViewState,
  type SearchScope,
  type SearchStatus,
  type SendChatInput,
  type TroubleshooterBranch,
  type TroubleshooterViewState,
} from "./view-model.ts";
export type {
  OllamaChatMessage,
  OllamaChatRequest,
  OllamaChatResponse,
  OllamaChatRole,
  OllamaClientErrorCode,
  OllamaCopyModelRequest,
  OllamaDeleteModelRequest,
  OllamaGenerateRequest,
  OllamaGenerateResponse,
  OllamaHealthResponse,
  OllamaHealthStatus,
  OllamaJsonObject,
  OllamaJsonValue,
  OllamaListModelsResponse,
  OllamaListRunningModelsResponse,
  OllamaLoopbackClientOptions,
  OllamaLoopbackHost,
  OllamaModelDetails,
  OllamaModelSummary,
  OllamaPullModelRequest,
  OllamaPullProgress,
  OllamaRequestOptions,
  OllamaRunningModelSummary,
  OllamaShowModelRequest,
  OllamaShowModelResponse,
  OllamaVersionResponse,
} from "./types.ts";
