// Generated by apps/site/build/sites-vite-plugin.ts. Do not edit by hand.
//
// The documentation browser and the changelog viewer read this file, which is
// produced from the tracked Markdown sources at build time. Regenerate it by
// running the site build; editing it directly lets the site drift from the
// repository it claims to describe.

import type { ChangelogEntry } from "@material-tax-reporting/surface-kernel";

export const CHANGELOG_ENTRIES: ChangelogEntry[] = [
  {
    "area": "desktop",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added a real Windows Electron desktop application with a plain-language, one-question-at-a-time tax-report wizard.",
    "commit": null,
    "verification": null
  },
  {
    "area": "desktop",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added an app-private Git repository that records each user-value mutation as one append-only encrypted snapshot commit. Restore and undo create new commits instead of rewriting history.",
    "commit": null,
    "verification": null
  },
  {
    "area": "desktop",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added a first-class history browser with action, date, and text filters, changed-path inspection, revision labels, restore, undo, and Git object-graph verification.",
    "commit": null,
    "verification": null
  },
  {
    "area": "desktop",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added a single bounded `.mtrproject` file containing authenticated encrypted state and attachments together with the complete local Git object database, refs, and history.",
    "commit": null,
    "verification": null
  },
  {
    "area": "desktop",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added project import preview actions for Create copy, Reconcile, and explicit Replace without silently overwriting an existing project file.",
    "commit": null,
    "verification": null
  },
  {
    "area": "desktop",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added atomic project-file writes, bounded entry and payload validation, normalized relative-member paths, per-member hashes, AES-256-GCM payload authentication, a password-wrapped portable data key using scrypt, and embedded Git graph validation.",
    "commit": null,
    "verification": null
  },
  {
    "area": "desktop",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added privileged packaged-resource discovery for the bundled offline OCR runtime. A missing-runtime status returns every searched location without PATH discovery or runtime downloads.",
    "commit": null,
    "verification": null
  },
  {
    "area": "desktop",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added an application-level preference record beside the app-private instances root and the protected key store. It is versioned, bounded and schema-validated, holds the preferences, per-element appearance overrides, tab layout, schedules, lock metadata and the notification and vocabulary pointers, and is never written into an encrypted project file or a history record.",
    "commit": null,
    "verification": null
  },
  {
    "area": "desktop",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added exactly one allowlisted subscription channel set to the preload boundary — transfer progress, local model state, notification pushes and applied schedules — with no wildcard channel.",
    "commit": null,
    "verification": null
  },
  {
    "area": "desktop",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added English, Hong Kong-style Cantonese and bilingual language modes with independent 1-to-5 humour levels per language and a separate non-semantic dialog-emoji switch. Fact-bearing strings are declared as fixed text, so a humour level cannot change a field name, a validation rule, a numeric limit or the mail-in-only boundary statement.",
    "commit": null,
    "verification": null
  },
  {
    "area": "desktop",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added a personal vocabulary control that accepts a bounded local JSON wording map, preserves the official names and the product boundary spans, keeps the parsed cache in the application data directory only, and adds a renamable shared mode that suppresses the non-English wording features while it is on.",
    "commit": null,
    "verification": null
  },
  {
    "area": "desktop",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added read-aloud narration that is off by default, enumerates installed voices, selects English and Cantonese voices independently, reports truthfully when no voice for a language is installed, and never reads the Social Insurance Number field, a mailing address, an unlock answer or an attachment display name.",
    "commit": null,
    "verification": null
  },
  {
    "area": "desktop",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added presentation schedules evaluated against a named time zone with the documented precedence order, an editor that reports which layer is winning and why, and an opt-in external presentation-settings path that reads only an allowlisted https origin in the privileged boundary and shows a received document as not applied until it validates.",
    "commit": null,
    "verification": null
  },
  {
    "area": "desktop",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added a bounded display name, a shipped-mark or local-image logo validated in the privileged boundary, and an About card stating that renaming is presentation only.",
    "commit": null,
    "verification": null
  },
  {
    "area": "desktop",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added a converter destination with the bundled adapters this build carries and disabled rows naming exactly what is missing for the ones it does not, bounded by the existing attachment size limit, writing only to a chosen folder, and stating that converted output still has to pass the manual parser-confirmation step.",
    "commit": null,
    "verification": null
  },
  {
    "area": "desktop",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added the privileged half of the local model suite behind named channels, rendering the shared package's state in the application's own chrome, with the honest unavailable states for an unreachable runtime, an empty or stale catalogue cache, an unknown hardware verdict, undetected executables, cart blockers and harness pre-flight blockers.",
    "commit": null,
    "verification": null
  },
  {
    "area": "desktop",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added a real tab model with all four docking edges, correct keyboard semantics per orientation, tablist roles with roving focus, an overflow menu with its own filter, pinning, groups and a bulk close that names the matched set before it runs.",
    "commit": null,
    "verification": null
  },
  {
    "area": "desktop",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added a shared-token palette with both dark paths and a complete reduced-motion path, plus a per-element appearance editor with typography controls, colour translation across every supported space with honest out-of-gamut reporting, bounded preset export and import, and a refusal for any override that would make a required disclosure unreadable.",
    "commit": null,
    "verification": null
  },
  {
    "area": "desktop",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added per-element and per-property presentation locks whose verifiers are derived and sealed in the privileged boundary, rate limited there, recorded in the append-only history, and refused outright on the review checklist, the boundary disclosure and the save and close controls.",
    "commit": null,
    "verification": null
  },
  {
    "area": "desktop",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added a standards-only authenticator utility that generates a pairing three ways on this computer, seals the shared secret with protected storage, and states plainly that there is no network, no email and no server-side recovery; and local support tickets whose bodies are redacted before storage.",
    "commit": null,
    "verification": null
  },
  {
    "area": "desktop",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added a notifications destination backed by a bounded local log with severity, recovery text, timestamp and originating action, search and filters, multi-select and scoped bulk actions that preview their exact scope, and in-application dialogs replacing the blocking browser confirmations and prompts.",
    "commit": null,
    "verification": null
  },
  {
    "area": "desktop",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added a packaged changelog record and a packaged documentation library generated by the application build, read at run time from allowlisted packaged locations only, rendered from a typed Markdown node list, with wizard steps deep-linking to the article that owns them.",
    "commit": null,
    "verification": null
  },
  {
    "area": "desktop",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added a command palette on Control, Shift and F and on a visible title-bar button, covering every destination, wizard question, project action, history action and personalization setting, operating setting results inline and teleporting to the exact element otherwise.",
    "commit": null,
    "verification": null
  },
  {
    "area": "desktop",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added one reusable anchored search builder instantiated independently beside every search, filter, picker and menu filter, with the append-only history store keeping plain substring matching unless an explicit validated pattern is passed.",
    "commit": null,
    "verification": null
  },
  {
    "area": "desktop",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added exports of the currently filtered view with a manifest stating the encoding, schema version, exact filter, row count and omissions, identity redaction on by default behind a typed confirmation, bulk actions that preview their scope, and an external-editor handoff that opens only the file just written or its folder.",
    "commit": null,
    "verification": null
  },
  {
    "area": "desktop",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added Start, Downloading and Complete surfaces for the transfers this application performs, with chunked project-container writes, a working cancel that removes the partial temporary file, and a completion surface that names the path, measured byte count and content hash while making no signature-authenticity claim.",
    "commit": null,
    "verification": null
  },
  {
    "area": "desktop",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added a bundled portable-document text-layer extractor, which turns the converter catalogue's portable-document row from a permanently disabled entry into an adapter the build can actually run. It inflates compressed streams with the runtime's own `zlib`, so it adds no dependency, stages no packaged resource and makes no network call; it locates objects by scanning rather than by following the cross-reference table, so an incrementally updated or slightly damaged file still reads, expands compressed object streams to reach the page tree, and decodes text through the font's ToUnicode map where one exists and Windows-1252 where one does not. It refuses instead of returning an empty file that reads as a successful conversion: a document carrying no text layer is refused by name and pointed at optical character recognition, which stays honestly disabled; an encrypted document is refused rather than decoded into confident mojibake; and a file that does not begin with a portable-document header is refused on its bytes rather than its extension. Extracted text is not confirmed tax data and still has to pass the manual parser-confirmation step.",
    "commit": null,
    "verification": null
  },
  {
    "area": "desktop",
    "version": "Unreleased",
    "date": null,
    "section": "Changed",
    "entry": "Removed three completion claims from the transfer surfaces that reported bytes and digests nothing had measured. The import-copy step, which deliberately writes nothing until the import is activated, no longer reports one fabricated byte to satisfy the shared state machine's refusal to complete without a measured byte count; it withdraws in its start phase and returns the chosen destination instead, and its card is labelled a destination rather than a copy. Conversion now reports the running byte total as each output lands, relays a cancellation from the surrounding transfer, and completes with a digest measured over the bytes actually on disk — a single output reporting that file's own hash and a batch reporting a manifest digest that is named as one rather than passed off as a file hash. Attachment intake reports the plaintext digest it was already computing and discarding.",
    "commit": null,
    "verification": null
  },
  {
    "area": "desktop",
    "version": "Unreleased",
    "date": null,
    "section": "Changed",
    "entry": "Corrected the transfer card's terminal copy, which worded every committed transfer as a write to a path and headed it complete, including the import-copy step that had just reported writing nothing. The card now takes its wording from the phase the main process reported: complete and a named path only where the state machine reached its complete phase, which it cannot do without a measured byte count; destination chosen, carrying the main process's own no-bytes-written-yet notice, where the plan was withdrawn; and nothing written, carrying the recorded reason, otherwise. A byte count and a digest appear only in the first case, and the digest sentence names what that digest covers, because a project container and an export are hashed over the bytes written, an attachment over the plaintext taken in before it is encrypted, and a converted batch carries a manifest hash rather than a file hash. A card that reached a failed progress event no longer removes itself twelve seconds after its terminal state is rendered.",
    "commit": null,
    "verification": null
  },
  {
    "area": "desktop",
    "version": "Unreleased",
    "date": null,
    "section": "Changed",
    "entry": "Repaired the application build, which could not run at all on the pinned toolchain. Its build script imports one changelog engine from the shared surface kernel, that package's entry point resolved to raw TypeScript, and the runtime that executes the script cannot load a `.ts` file, so the build died on line six with `ERR_UNKNOWN_FILE_EXTENSION` before it compiled anything. The shared package now offers Node a compiled entry, and this package gained a `prebuild` step that produces it, so ordering is wired once and every route into the application build inherits it: the workspace build, the repository-root build script, the start script, and the committed batch entry points the release path invokes. The two must stay together — separating the import from the step that compiles what it imports puts the build straight back into a first-import failure.",
    "commit": null,
    "verification": null
  },
  {
    "area": "desktop",
    "version": "Unreleased",
    "date": null,
    "section": "Boundaries",
    "entry": "The application prepares information for a manually reviewed CRA mail-in PDF package only. It does not provide NETFILE, EFILE, electronic submission, direct CRA transmission, or automatic filing.",
    "commit": null,
    "verification": null
  },
  {
    "area": "desktop",
    "version": "Unreleased",
    "date": null,
    "section": "Boundaries",
    "entry": "No browser-extension download capture exists in this repository and none is claimed. The transfer surfaces cover only the local transfers the application genuinely performs.",
    "commit": null,
    "verification": null
  },
  {
    "area": "desktop",
    "version": "Unreleased",
    "date": null,
    "section": "Boundaries",
    "entry": "No installer, release asset, tag or download control is produced by this change.",
    "commit": null,
    "verification": null
  },
  {
    "area": "desktop",
    "version": "Unreleased",
    "date": null,
    "section": "Verification",
    "entry": "Run and observed: `npm run build --workspace @material-tax-reporting/desktop` completed and wrote the main, preload, renderer, changelog, documentation-manifest and provenance outputs.",
    "commit": null,
    "verification": null
  },
  {
    "area": "desktop",
    "version": "Unreleased",
    "date": null,
    "section": "Verification",
    "entry": "Run and observed: the generated main and preload bundles were parsed with the Node syntax checker, and the inlined renderer bundle was parsed as a script; all three parsed without error.",
    "commit": null,
    "verification": null
  },
  {
    "area": "desktop",
    "version": "Unreleased",
    "date": null,
    "section": "Verification",
    "entry": "Not run, and therefore not claimed: tests, lint, type checks, packaging, installer creation, release, application launch, screenshots, accessibility conformance checks, performance measurements and native-speaker language review.",
    "commit": null,
    "verification": null
  },
  {
    "area": "desktop",
    "version": "Unreleased",
    "date": null,
    "section": "Verification",
    "entry": "The earlier statement that no build was run applies to the previous implementation lane recorded above; it is superseded for this change by the two run-and-observed lines.",
    "commit": null,
    "verification": null
  },
  {
    "area": "desktop",
    "version": "Unreleased",
    "date": null,
    "section": "Verification",
    "entry": "Run and observed for the transfer-card copy correction recorded under Changed: `npm run build --workspace @material-tax-reporting/desktop` completed with exit status 0, and the generated main bundle, preload bundle and inlined renderer script were each parsed without error afterwards.",
    "commit": null,
    "verification": null
  },
  {
    "area": "desktop",
    "version": "Unreleased",
    "date": null,
    "section": "Verification",
    "entry": "Not run, and therefore not claimed, for the entries recorded in this set: tests, lint, type checks, packaging, installer creation, release, application launch, screenshots, accessibility conformance checks and performance measurements. The transfer surfaces were not exercised at run time, so the corrected terminal wording has not been observed rendering, and the portable-document extractor's own conversion results were not re-run here.",
    "commit": null,
    "verification": null
  },
  {
    "area": "docs",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added `docs/features/feature-inventory.json`, the repository's hand-written feature-completeness record: one row per capability per surface, naming its implementation files, its documentation article, its changelog, its tests, the interaction a person would have to perform to exercise it, its capture evidence, its relation to the paper-only product boundary, and its explicit evidence gaps.",
    "commit": null,
    "verification": "the four results below were observed by the lanes that produced them, and the inventory was parsed and its paths checked; no application was launched and no capture was taken."
  },
  {
    "area": "docs",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added the inventory's evidence policy, which states that a row may claim runtime or capture evidence only after a real built surface was exercised, and that reading source never upgrades a pending row.",
    "commit": null,
    "verification": "the four results below were observed by the lanes that produced them, and the inventory was parsed and its paths checked; no application was launched and no capture was taken."
  },
  {
    "area": "docs",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added `docs/features/README.md` as the index for the feature tree: how to read the inventory, what each state value means, which subtree owns which surface, and the rule that an article describes shipped behaviour only, with anything unbuilt confined to a clearly labelled \"Not yet available\" heading rather than written in the present tense.",
    "commit": null,
    "verification": "the four results below were observed by the lanes that produced them, and the inventory was parsed and its paths checked; no application was launched and no capture was taken."
  },
  {
    "area": "docs",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added the public wording contract to `docs/features/README.md`. It states, once and for the whole repository, the ten rules every user-visible string already had to satisfy: ordinary professional English, the permanent filing boundary, no unearned verification claim, no fabricated tax content, visible separation of intent from shipped behaviour, sourced tax statements, no premature download, one product name, bilingual copy that agrees on facts, and synchronized manifests and lockfiles.",
    "commit": null,
    "verification": "the four results below were observed by the lanes that produced them, and the inventory was parsed and its paths checked; no application was launched and no capture was taken."
  },
  {
    "area": "docs",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added a website feature inventory table to `docs/site/README.md` with one row per capability the website's source implements, each carrying the state the machine-readable inventory holds and pointing at the article that owns it.",
    "commit": null,
    "verification": "the four results below were observed by the lanes that produced them, and the inventory was parsed and its paths checked; no application was launched and no capture was taken."
  },
  {
    "area": "docs",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added a \"What was verified\" section to `docs/site/verification-status.md` naming the four checks that were actually run and their observed results.",
    "commit": null,
    "verification": "the four results below were observed by the lanes that produced them, and the inventory was parsed and its paths checked; no application was launched and no capture was taken."
  },
  {
    "area": "docs",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added a local-wording privacy bullet to `docs/site/local-first-privacy.md` stating that a personal vocabulary, display name, or mark stays in the visitor's own browser and can never rewrite a legal, boundary, or disclosure sentence.",
    "commit": null,
    "verification": "the four results below were observed by the lanes that produced them, and the inventory was parsed and its paths checked; no application was launched and no capture was taken."
  },
  {
    "area": "docs",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added pointers from `docs/site/installer-and-releases.md` to the website and desktop transfer-surface articles, recording that the release manifest carries no assets and that the site therefore renders its unavailable state.",
    "commit": null,
    "verification": "the four results below were observed by the lanes that produced them, and the inventory was parsed and its paths checked; no application was launched and no capture was taken."
  },
  {
    "area": "docs",
    "version": "Unreleased",
    "date": null,
    "section": "Changed",
    "entry": "Corrected the \"Project state\" section of `AGENTS.md`, which said there is no shipped application, installer, tax engine, PDF generator, documentation site, test suite, or release workflow. It now records that implementation source exists for the documentation site, the desktop application, and the `surface-kernel`, `tax-domain`, `cra-pdf`, `slip-parser`, `local-ollama`, and `local-coding-assistants` packages, that a workflow which builds and publishes the documentation site is defined at `.github/workflows/pages.yml`, and that no installer, release asset, download control, or verified build exists. Every other rule in that file is unchanged.",
    "commit": null,
    "verification": "the four results below were observed by the lanes that produced them, and the inventory was parsed and its paths checked; no application was launched and no capture was taken."
  },
  {
    "area": "docs",
    "version": "Unreleased",
    "date": null,
    "section": "Changed",
    "entry": "Corrected the \"Current stage\" section of `CONTRIBUTING.md`, which said the repository contains only governance, workspace manifests, and bootstrap entry points.",
    "commit": null,
    "verification": "the four results below were observed by the lanes that produced them, and the inventory was parsed and its paths checked; no application was launched and no capture was taken."
  },
  {
    "area": "docs",
    "version": "Unreleased",
    "date": null,
    "section": "Changed",
    "entry": "Corrected the \"Development commands\" section of `CONTRIBUTING.md`, which said there is no runnable build or test suite. It now names the workspace commands that exist and states that there is no repository-wide test, lint, type-check, accessibility, or packaging command. The fail-closed statement about `build.bat` and `build-installer.bat` is kept, and a nonzero exit from them remains the correct result.",
    "commit": null,
    "verification": "the four results below were observed by the lanes that produced them, and the inventory was parsed and its paths checked; no application was launched and no capture was taken."
  },
  {
    "area": "docs",
    "version": "Unreleased",
    "date": null,
    "section": "Changed",
    "entry": "Corrected the repository map in `README.md`, which called `apps/site`, `packages/tax-domain`, and `packages/cra-pdf` reserved workspaces and omitted `packages/slip-parser` and `packages/surface-kernel` entirely. Each row now describes the source the directory actually contains.",
    "commit": null,
    "verification": "the four results below were observed by the lanes that produced them, and the inventory was parsed and its paths checked; no application was launched and no capture was taken."
  },
  {
    "area": "docs",
    "version": "Unreleased",
    "date": null,
    "section": "Changed",
    "entry": "Resolved the contradiction that followed that map, which stated both that the repository includes the packages' source and that they were reserved. The paragraph now states plainly that everything listed is source, and that nothing in the repository establishes that either application was built for distribution, packaged, installed, launched, or exercised by a person.",
    "commit": null,
    "verification": "the four results below were observed by the lanes that produced them, and the inventory was parsed and its paths checked; no application was launched and no capture was taken."
  },
  {
    "area": "docs",
    "version": "Unreleased",
    "date": null,
    "section": "Changed",
    "entry": "Replaced the project-status note in `README.md` and added a documentation index and a development-status section naming the workspace commands.",
    "commit": null,
    "verification": "the four results below were observed by the lanes that produced them, and the inventory was parsed and its paths checked; no application was launched and no capture was taken."
  },
  {
    "area": "docs",
    "version": "Unreleased",
    "date": null,
    "section": "Changed",
    "entry": "Corrected the opening statement of `docs/site/verification-status.md`, which described the change as the initial public website documentation change, and rewrote \"what was not run\" and \"what is not yet verified\" to match the current state: implementation source exists, while browser behaviour, accessibility conformance, responsive layout, packaging, and deployment remain unverified.",
    "commit": null,
    "verification": "the four results below were observed by the lanes that produced them, and the inventory was parsed and its paths checked; no application was launched and no capture was taken."
  },
  {
    "area": "docs",
    "version": "Unreleased",
    "date": null,
    "section": "Changed",
    "entry": "Expanded `docs/site/website-preferences-and-search.md`. Its single clause about an anchored regular-expression builder beside the search field is now a pointer to the articles that own the engine and its bindings, and its vague line about \"presentation choices such as theme and navigation state\" now names the real preference record and the stores that sit beside it.",
    "commit": null,
    "verification": "the four results below were observed by the lanes that produced them, and the inventory was parsed and its paths checked; no application was launched and no capture was taken."
  },
  {
    "area": "docs",
    "version": "Unreleased",
    "date": null,
    "section": "Verification",
    "entry": "The shared surface-kernel package compiled with no diagnostics and its 89 tests passed.",
    "commit": null,
    "verification": "the four results below were observed by the lanes that produced them, and the inventory was parsed and its paths checked; no application was launched and no capture was taken."
  },
  {
    "area": "docs",
    "version": "Unreleased",
    "date": null,
    "section": "Verification",
    "entry": "The local model package compiled with no diagnostics and its 37 tests passed, along with the 6 tests of the local coding-assistant package.",
    "commit": null,
    "verification": "the four results below were observed by the lanes that produced them, and the inventory was parsed and its paths checked; no application was launched and no capture was taken."
  },
  {
    "area": "docs",
    "version": "Unreleased",
    "date": null,
    "section": "Verification",
    "entry": "The website's production build completed and emitted its static bundle.",
    "commit": null,
    "verification": "the four results below were observed by the lanes that produced them, and the inventory was parsed and its paths checked; no application was launched and no capture was taken."
  },
  {
    "area": "docs",
    "version": "Unreleased",
    "date": null,
    "section": "Verification",
    "entry": "The desktop application's build completed and all of its generated bundles parsed.",
    "commit": null,
    "verification": "the four results below were observed by the lanes that produced them, and the inventory was parsed and its paths checked; no application was launched and no capture was taken."
  },
  {
    "area": "docs",
    "version": "Unreleased",
    "date": null,
    "section": "Verification",
    "entry": "`docs/features/feature-inventory.json` was parsed, and every one of the 299 repository-relative paths across its 49 rows was confirmed to exist; the parse also confirmed that no row is duplicated for a surface, that every state is one of the three allowed values, and that no row claims capture evidence.",
    "commit": null,
    "verification": "the four results below were observed by the lanes that produced them, and the inventory was parsed and its paths checked; no application was launched and no capture was taken."
  },
  {
    "area": "docs",
    "version": "Unreleased",
    "date": null,
    "section": "Verification",
    "entry": "Not run for this change: any launch of the website or the desktop application, any screenshot, recording, or other capture, any lint check, any type check beyond the packages' own compilation, any accessibility check, any browser-based or desktop-based user-interface quality assurance, any packaging, installer, tag, or release step, and any performance measurement or native-speaker review.",
    "commit": null,
    "verification": "the four results below were observed by the lanes that produced them, and the inventory was parsed and its paths checked; no application was launched and no capture was taken."
  },
  {
    "area": "local-coding-assistants",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added executable discovery and bounded version probing for local Codex CLI and OpenCode installations without relying on PATH alone.",
    "commit": null,
    "verification": null
  },
  {
    "area": "local-coding-assistants",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added enumerated read-only and workspace-writing profiles with guided recommended defaults.",
    "commit": null,
    "verification": null
  },
  {
    "area": "local-coding-assistants",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added selected-context prompt construction, sensitive-data redaction, exact preview and provider-network acknowledgements, and fail-closed launch preflight.",
    "commit": null,
    "verification": null
  },
  {
    "area": "local-coding-assistants",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added direct allowlisted process launch contracts that prohibit arbitrary shell text, command concatenation, unvalidated environment expansion, and unapproved working directories.",
    "commit": null,
    "verification": null
  },
  {
    "area": "local-coding-assistants",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Preserved the no-electronic-filing boundary, mandatory manual mail-in PDF review, and taxpayer-review requirement in every prompt and preflight.",
    "commit": null,
    "verification": null
  },
  {
    "area": "local-coding-assistants",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added `test/launch-preflight.test.ts`, an executable regression proving the launch-plan assertion refuses a mutated argument list, a replaced sandbox argument, an added environment override, a working directory outside the allowed roots, and an executable missing from the current discovery results — in every case without reaching the process launcher.",
    "commit": null,
    "verification": null
  },
  {
    "area": "local-coding-assistants",
    "version": "Unreleased",
    "date": null,
    "section": "Verification",
    "entry": "`node --test --experimental-strip-types packages/local-coding-assistants/test/*.test.ts` — 6 tests passed, 0 failed.",
    "commit": null,
    "verification": null
  },
  {
    "area": "ollama",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added a portable view-model (`src/view-model.ts`) that describes the whole suite as state plus actions, so the documentation site surface and the desktop surface can each render it inside their own shell.",
    "commit": null,
    "verification": null
  },
  {
    "area": "ollama",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added guided real-data choices: detected harness executables with an explicit `unchecked`, `checking`, `none-detected` or `detected` state and a named recovery action; chat and harness model lists enumerated from the installed models; catalog family, capability and quantization facets derived from the cached snapshot; and a troubleshooter branch for every runtime condition, each with an offline next step and a recheck.",
    "commit": null,
    "verification": null
  },
  {
    "area": "ollama",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added a batch cart that sums the reviewed variants, applies the same temporary-file headroom as the pull queue, compares the total against measured free space, states any shortfall in exact bytes before commit, and enqueues the whole batch in one pass through the new `PersistentPullQueue.enqueueBatch`.",
    "commit": null,
    "verification": null
  },
  {
    "area": "ollama",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added capability-gated chat attachments: attachments now reach the chat manager's existing image-capability gate and decoded byte ceiling, and the rejection message is surfaced on its own state field.",
    "commit": null,
    "verification": null
  },
  {
    "area": "ollama",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added one-click harness snapshot restore, backed by a new `list` method on the snapshot store port and `listExecutables` and `listSnapshots` methods on the harness manager. Restore resolves an identifier against the loaded list and never accepts a caller-supplied payload.",
    "commit": null,
    "verification": null
  },
  {
    "area": "ollama",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added an independent search state for every filterable collection — catalog variants, installed models, the pull queue, the chat history, harness profiles and harness snapshots — so a host can attach one builder per collection.",
    "commit": null,
    "verification": null
  },
  {
    "area": "ollama",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added a `test/` suite of executable negative regressions covering catalog completeness, hardware-fit evidence, commerce vocabulary, harness shell and rollback behaviour, chat attachment capability, guided choices, and batch storage preflight.",
    "commit": null,
    "verification": null
  },
  {
    "area": "ollama",
    "version": "Unreleased",
    "date": null,
    "section": "Changed",
    "entry": "Replaced the full-page renderer with the view-model. `mountLocalOllamaSuiteSurface`, every DOM helper, and `src/surface.css` were removed; the package no longer compiles against DOM types.",
    "commit": null,
    "verification": null
  },
  {
    "area": "ollama",
    "version": "Unreleased",
    "date": null,
    "section": "Changed",
    "entry": "Replaced the package's own pattern and flag validation, and the separate regular expression compiled inside `filterCatalogVariants`, with the shared anchored search engine from `@material-tax-reporting/surface-kernel`.",
    "commit": null,
    "verification": null
  },
  {
    "area": "ollama",
    "version": "Unreleased",
    "date": null,
    "section": "Changed",
    "entry": "Runtime probes now report the failing local API check names as a list, so the active troubleshooter branch can display them.",
    "commit": null,
    "verification": null
  },
  {
    "area": "ollama",
    "version": "Unreleased",
    "date": null,
    "section": "Changed",
    "entry": "Narrowed the compiler library set from `ES2022, DOM, DOM.Iterable` to `ES2022, WebWorker`. Document and element types are now compile errors, while the web-standard networking types the loopback client genuinely uses — `fetch`, `Response`, `AbortSignal`, `URL`, `TextDecoder` — remain available.",
    "commit": null,
    "verification": null
  },
  {
    "area": "ollama",
    "version": "Unreleased",
    "date": null,
    "section": "Changed",
    "entry": "Relative imports inside the package now name the TypeScript source, matching the shared kernel, so the package's own test script can run the sources directly.",
    "commit": null,
    "verification": null
  },
  {
    "area": "ollama",
    "version": "Unreleased",
    "date": null,
    "section": "Fixed",
    "entry": "Fixed two long-standing type errors that prevented the package from compiling: the running-model listing being passed to a parameter typed for the installed-model listing, and an optional abort signal being handed to `fetch` under `exactOptionalPropertyTypes`.",
    "commit": null,
    "verification": null
  },
  {
    "area": "ollama",
    "version": "Unreleased",
    "date": null,
    "section": "Verification",
    "entry": "`tsc -p packages/local-ollama/tsconfig.json --noEmit` — no errors.",
    "commit": null,
    "verification": null
  },
  {
    "area": "ollama",
    "version": "Unreleased",
    "date": null,
    "section": "Verification",
    "entry": "`node --test --experimental-strip-types packages/local-ollama/test/*.test.ts` — 37 tests passed, 0 failed.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Moved every user-facing string into one copy bundle with five humour levels per language, and added a source check that runs the shared kernel's fact invariant so humour can change tone but never a number, a date, an official name, a link or an action label.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added a decorative dialog emoji preference that marks the emoji as hidden from assistive technology and never lets it replace a word.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Applied the personal-vocabulary map to every string the site renders instead of two call sites, moved its validation to the shared kernel, and protected the official reference wording and addresses, the paper-only boundary sentence and the disclaimers as immutable spans.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added a source check that fails when a built-in vocabulary map, example or private default appears in the application sources.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added read-aloud over the browser's own speech synthesis, driven by the shared kernel's narration queue so bilingual output is strictly serialized, started only from an explicit control, and disabled with the exact reported reason when a browser exposes no speech synthesis or no installed voices.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added scheduled presentation rules that contribute an overlay rather than overwriting the stored preference, evaluated on one interval and again when the tab becomes visible, with the shared kernel resolving precedence between a hold placed by hand, an active rule, the external document and the stored preference.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added a hold, so a setting changed by hand while a rule is setting it keeps the chosen value: the hold is stored under its own key in this browser, survives a reload, is recorded in local history and announced as a notification, and is listed in the schedule panel with a `Follow the schedule rule again` control that also appears on the settings card whose value it decides. A hold expires by itself once nothing is scheduling that setting, so the rule's next window still applies.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added an opt-in external presentation-settings source, off by default, restricted to a complete https address, bounded by an abort timeout, validated against the shared kernel's bounded schema, limited to presentation values, and falling back to the local rules with the exact reason on any failure.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added a display name and a mark for this browser, with local images validated by the shared kernel for declared type, declared length and leading bytes, and vector markup rejected. The shared page title is left as the shipped product name.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added a file converter for this site's own records, registering shared-kernel adapters for the personal-vocabulary map, the documentation index, the changelog view and the notification history, with a per-file preview before anything is written, a working cancel, and a named reason for every rejected file.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added a local model runtime surface that reports only what a browser probe observed, names the actual probe failure, and never renders a connected or healthy state that was not observed.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Promoted the tab strip to persisted state driven by the shared kernel tab model, with keyboard and pointer reordering, pinning, named collapsible groups, a move picker, a resize-observed overflow menu button in place of a horizontal scroll region, and a bulk close that names the exact matched set before it acts.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added a per-element appearance editor emitting scoped custom properties, reachable from a context menu and from the command palette, with typography and colour controls, preset export and bounded preset import, and reset for one property or for a whole element.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added a colour translator covering hexadecimal, rgb, hsl, hwb, lab, lch, oklab, oklch and named colours, reporting out-of-gamut results and the computed contrast ratio against the resolved surface with an explicit pass or fail.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added element locks bound to the shared kernel, refusing a preference write through one guarded setter and withholding a locked setting from the schedule overlay, counting incorrect attempts, relocking on a timer that is re-checked when the tab becomes visible, and repeating the kernel's disclosure that a lock is a presentation guard with no security property.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added a local authenticator utility that draws its QR image from the shared kernel's encoder as inline vector shapes, with no external image and no network access, labelled as bound to no account because this site has no accounts.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added browser-local support notes with shared-kernel redaction on save and a visible statement that notes stay in this browser and are never transmitted.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added append-only local history over the browser's indexed database, recording every preference, appearance, tab, lock, schedule, ticket, export and vocabulary change, with a date range filter, an action filter, per-entry differences, a restore that writes a new record and names the values it would reapply, and a documented cap with a visible prune control.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Rebuilt the notification centre with kinds, read state, full timestamps, assertive announcement for errors, persistent progress notices, per-row selection with select-all-visible and shift-range, bulk mark-read and bulk dismiss behind a confirmation that states the exact count, and an unread-only badge.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added a changelog viewer generated at build time from the tracked changelog files, grouped by area and release, with a search, an area filter, a real date range, an export, each release's verification block shown verbatim, and a commit link only where a real identifier exists.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Replaced the six hard-coded summary cards with a documentation browser generated at build time from the tracked Markdown, working offline from the bundle with no runtime fetch, with a filterable index, resolved internal links, a heading outline, matched-heading context in results, and a feature library whose state statements are read from the tracked verification-status article.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Generated the command palette from the same declarative sources as the settings grid, the tab strip, the appearance store, the documentation index and the changelog, added live inline controls for every preference, fixed teleport so a command lands in the field it names, moved focus to the palette field on open, trapped Tab inside the dialog, and restored focus to the invoking control on close.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added a source check that reports any preference key the command palette cannot reach.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Repointed every search at the shared kernel engine, deleted the site's duplicate matcher and analyser, attached an independent anchored builder to every search, filter, picker and menu filter, added Escape-to-close that returns focus to the originating field, and added a source check that fails when any module renders its own search input.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added exports in four formats through the shared kernel, each stamped with the exact filter that produced it, with a folder-choosing save where the browser supports it, a download fallback, a clipboard path, and an honest statement of the browser limitation instead of an editor button that cannot work.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added a shared selection layer with per-row checkboxes, select-all-visible, shift-range selection and a live count, and gated every destructive bulk action behind a confirmation naming the exact count.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added the Start, Downloading and Complete transfer surfaces driven by an empty release manifest, so the site keeps rendering its honest unavailable state and the counts shown on the home surface are derived from the manifest rather than hard-coded.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added the website feature documentation set under `docs/features/site/`, one article per shipped capability.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Unreleased",
    "date": null,
    "section": "Fixed",
    "entry": "Fixed the documented manual-over-rule precedence, which was described in three places and implemented in none. The site called the kernel's `resolvePrecedence` with an empty override map, so an active rule always won and every settings control that rule named was inert: choosing the value the rule was hiding diffed against an unchanged stored preference, wrote nothing, recorded nothing, announced nothing, and left the control showing the rule's value. A change made by hand now records a hold that the kernel resolves as the manual layer, and the settings card reports which of the four layers its value came from.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Unreleased",
    "date": null,
    "section": "Fixed",
    "entry": "Fixed an element lock being bypassed by a schedule rule naming the same setting. A comment asserted that every mutation, a scheduled rule included, was routed through one guarded setter; a rule never writes the stored preference at all, so it never reached that setter and changed a locked setting freely. A locked setting is now withheld from the overlay, the external document and any hold, resolving from the stored preference alone, and the comment describes the two guards that exist rather than the one that did not.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Unreleased",
    "date": null,
    "section": "Changed",
    "entry": "Routed a saved converter result through the shared export delivery instead of a second blob path of its own, so it is written to a chosen folder where the browser offers that interface, reports the file name, size and path it took, is recorded in local history, and carries the same manifest every other collection carries. A comma-separated or tab-separated result carries the manifest as leading `#` comment lines the converter's own reader discards, and a Markdown result as a heading and a bullet list; a vocabulary JSON result is written unchanged and says why, because the vocabulary schema accepts only its version and replacements fields and would refuse a stamped document on the way back in. The website's sources now create a temporary object address in exactly one place.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Unreleased",
    "date": null,
    "section": "Changed",
    "entry": "Gave a saved converter result the target format's own extension and media type in place of the previous plain-text type for every target, and recorded the source and target formats on each result so choosing a different conversion after a batch has run can no longer mislabel what is saved.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Unreleased",
    "date": null,
    "section": "Changed",
    "entry": "Replaced the site's own preference record with the shared kernel record, migrating an existing version 1 record once so a visitor keeps their dock, theme, density, accent, font scale, motion, language and humour choices.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Unreleased",
    "date": null,
    "section": "Changed",
    "entry": "Imported the shared kernel token stylesheet once and stamped the theme, density and motion choice on the document element so the shared tokens and the site palette resolve to the same values.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Unreleased",
    "date": null,
    "section": "Changed",
    "entry": "Narrowed the unavailable-feature statement to the capabilities that are genuinely absent, and moved the honest capability inventory into the documentation browser's feature library, where each row links to its article and repeats what the tracked verification-status article records as not run.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Unreleased",
    "date": null,
    "section": "Changed",
    "entry": "Replaced the silent forty-item truncation of local activity with a documented cap and a visible prune control.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Unreleased",
    "date": null,
    "section": "Changed",
    "entry": "Cleared the toast dismissal timer in a cleanup effect instead of leaving it running.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Unreleased",
    "date": null,
    "section": "Changed",
    "entry": "Extended the site build plugin to generate the documentation and changelog modules from the tracked Markdown, so neither view can drift from the repository.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Unreleased",
    "date": null,
    "section": "Changed",
    "entry": "Resolved the workspace packages by absolute path in the site build configuration so one package can import another without a duplicated installation.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Backfilled: website implementation that was never recorded",
    "date": null,
    "section": "Added",
    "entry": "A Material 3 shell with a sticky header, a dockable tab strip, a content area and a footer, laid out with CSS grid.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Backfilled: website implementation that was never recorded",
    "date": null,
    "section": "Added",
    "entry": "Local browser preferences for theme, tab docking edge, density, accent colour, font scale, motion, language mode and two humour levels.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Backfilled: website implementation that was never recorded",
    "date": null,
    "section": "Added",
    "entry": "A responsive layout that collapses two-column reading surfaces below 1050 pixels and moves the tab strip to the top edge below 760 pixels.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Backfilled: website implementation that was never recorded",
    "date": null,
    "section": "Added",
    "entry": "A reduced-motion path for an explicit reduced-motion choice and for a system preference while the site follows the system.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Backfilled: website implementation that was never recorded",
    "date": null,
    "section": "Added",
    "entry": "A skip link, a focus-visible double ring on every interactive control, and a roving tabindex with arrow, Home and End handling on the tab strip.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Backfilled: website implementation that was never recorded",
    "date": null,
    "section": "Added",
    "entry": "A documentation search with an anchored regular-expression builder, a bounded sample area and a local match list.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Backfilled: website implementation that was never recorded",
    "date": null,
    "section": "Added",
    "entry": "A keyboard command palette on `Ctrl+Shift+F` with a visible fallback button.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Backfilled: website implementation that was never recorded",
    "date": null,
    "section": "Added",
    "entry": "A toast region and a notification history panel.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Backfilled: website implementation that was never recorded",
    "date": null,
    "section": "Added",
    "entry": "A validated personal-vocabulary upload, limited to 64 KB, 200 replacements, keys of 1 to 80 characters and values of at most 200 characters, rejecting unsafe object keys and unknown fields.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Backfilled: website implementation that was never recorded",
    "date": null,
    "section": "Added",
    "entry": "An honest installer-unavailable card and an honest inventory of unavailable capabilities.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Earlier documentation-only change",
    "date": null,
    "section": "Added",
    "entry": "Created the initial public documentation structure for the Material Tax Reporting website.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Earlier documentation-only change",
    "date": null,
    "section": "Added",
    "entry": "Documented the intended Canadian tax-report preparation scope and the Canada and Ontario jurisdiction boundary.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Earlier documentation-only change",
    "date": null,
    "section": "Added",
    "entry": "Documented the local-first privacy requirement and distinguished product intent from runtime verification.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Earlier documentation-only change",
    "date": null,
    "section": "Added",
    "entry": "Documented website preferences, responsive tabbed navigation, documentation search, and the anchored regular-expression builder.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Earlier documentation-only change",
    "date": null,
    "section": "Added",
    "entry": "Added an explicit installer-unavailable policy that prevents a download link from appearing before a release asset is verified.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Earlier documentation-only change",
    "date": null,
    "section": "Added",
    "entry": "Added a verification-status article that records what is and is not currently proven.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Earlier documentation-only change",
    "date": null,
    "section": "Added",
    "entry": "Defined the permanent paper-only product boundary: no NETFILE, EFILE, electronic submission, direct CRA transmission, automatic filing, or simulated submission.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Earlier documentation-only change",
    "date": null,
    "section": "Added",
    "entry": "Documented that the application ends with generation of a CRA mail-in PDF package.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Earlier documentation-only change",
    "date": null,
    "section": "Added",
    "entry": "Added the mandatory pre-export and pre-print review workflow covering every populated form, calculation, attachment, mailing destination, and signature field, followed by explicit user acknowledgement.",
    "commit": null,
    "verification": null
  },
  {
    "area": "site",
    "version": "Earlier documentation-only change",
    "date": null,
    "section": "Added",
    "entry": "Linked current official CRA paper-filing, mailing-destination, tax-package, and Ontario guidance without hard-coding mailing addresses or changing figures.",
    "commit": null,
    "verification": null
  },
  {
    "area": "slip-parser",
    "version": "Unreleased",
    "date": null,
    "section": "Changed",
    "entry": "Added a local-only TypeScript package for bounded PDF and image admission using byte and structural signature inspection.",
    "commit": null,
    "verification": null
  },
  {
    "area": "slip-parser",
    "version": "Unreleased",
    "date": null,
    "section": "Changed",
    "entry": "Added a fail-closed adapter registry that enables only package-declared bundled offline artifacts.",
    "commit": null,
    "verification": null
  },
  {
    "area": "slip-parser",
    "version": "Unreleased",
    "date": null,
    "section": "Changed",
    "entry": "Added bundled offline English and French OCR for PNG, JPEG, WebP, and scanned PDF pages using pinned Tesseract.js, PDF.js, and Windows canvas packages, with no `PATH` lookup, runtime download, URL input, cloud fallback, telemetry, or network route. TIFF remains admission-checked and fails closed because the bundled decoder does not claim a memory-bounded TIFF path.",
    "commit": null,
    "verification": null
  },
  {
    "area": "slip-parser",
    "version": "Unreleased",
    "date": null,
    "section": "Changed",
    "entry": "Added bounded sequential PDF rasterization, process-wide OCR concurrency and memory reservations, cancellation and timeout termination, deterministic raster/language/PDF/worker cleanup, and atomic rejection without partial output.",
    "commit": null,
    "verification": null
  },
  {
    "area": "slip-parser",
    "version": "Unreleased",
    "date": null,
    "section": "Changed",
    "entry": "Added source-relative geometry, confidence, source digest, raster-page digest, token evidence digest, and document extraction-evidence digest, plus mandatory acknowledgement of that evidence during side-by-side confirmation.",
    "commit": null,
    "verification": null
  },
  {
    "area": "slip-parser",
    "version": "Unreleased",
    "date": null,
    "section": "Changed",
    "entry": "Added an installer staging manifest and script that copies the complete offline runtime closure, verifies worker/core/WASM/language/PDF/native assets, and records per-file byte sizes and SHA-256 digests.",
    "commit": null,
    "verification": null
  },
  {
    "area": "slip-parser",
    "version": "Unreleased",
    "date": null,
    "section": "Changed",
    "entry": "Added bounded uncompressed PDF text-layer extraction with page coordinates and confidence evidence.",
    "commit": null,
    "verification": null
  },
  {
    "area": "slip-parser",
    "version": "Unreleased",
    "date": null,
    "section": "Changed",
    "entry": "Added tax-year and slip-type classification for T4, T4A, T4E, T5, T3, T5008, T2202, and RRSP contribution receipts.",
    "commit": null,
    "verification": null
  },
  {
    "area": "slip-parser",
    "version": "Unreleased",
    "date": null,
    "section": "Changed",
    "entry": "Added official CRA mapping metadata with formula and review-only distinctions for contextual relationships.",
    "commit": null,
    "verification": null
  },
  {
    "area": "slip-parser",
    "version": "Unreleased",
    "date": null,
    "section": "Changed",
    "entry": "Added digest-bound side-by-side manual confirmation that covers every candidate, ambiguity, warning, and final mail-in review item before a new return-entry projection can be created.",
    "commit": null,
    "verification": null
  },
  {
    "area": "slip-parser",
    "version": "Unreleased",
    "date": null,
    "section": "Changed",
    "entry": "Documented that the product supports only a CRA mail-in PDF package after mandatory manual review and does not support NETFILE, EFILE, electronic submission, direct CRA transmission, or automatic filing.",
    "commit": null,
    "verification": null
  },
  {
    "area": "surface-kernel",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added `@material-tax-reporting/surface-kernel`, a dependency-free TypeScript package compiled against the ES2022 standard library only, so React, Electron and DOM types cannot enter the shared layer.",
    "commit": null,
    "verification": null
  },
  {
    "area": "surface-kernel",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added `ports.ts` with the key-value store, clock, identifier, byte-source, abort-signal and Web Cryptography interfaces every stateful engine receives, plus system and fixed implementations for use in tests.",
    "commit": null,
    "verification": null
  },
  {
    "area": "surface-kernel",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added one anchored regular-expression search engine with a flag allowlist, bounded pattern and sample lengths, a zero-width match guard, global-flag semantics fixed per purpose, and a builder palette that includes explicit start-anchor and end-anchor tokens.",
    "commit": null,
    "verification": null
  },
  {
    "area": "surface-kernel",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added the shared preference record, its validator, its patch helper, and versioned storage keys with an upgrade from the previously shipped version 1 preference record.",
    "commit": null,
    "verification": null
  },
  {
    "area": "surface-kernel",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added language resolution across five humour levels per language and `assertFactsInvariant`, which reports copy keys whose humour variants disagree on a fact-bearing token.",
    "commit": null,
    "verification": null
  },
  {
    "area": "surface-kernel",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added personal-vocabulary validation, compilation and single-pass whole-token substitution with immutable spans that are never rewritten.",
    "commit": null,
    "verification": null
  },
  {
    "area": "surface-kernel",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added the command registry, its search, its teleport target resolution, and a coverage check that reports preference keys no command can reach.",
    "commit": null,
    "verification": null
  },
  {
    "area": "surface-kernel",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added notification state with the rule that progress and error notices never auto-dismiss, plus filtering and bulk-scope selection.",
    "commit": null,
    "verification": null
  },
  {
    "area": "surface-kernel",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added the append-only history model: the widened action list, redaction rules, filtering, a cap helper, and a restore that returns a new record without mutating the supplied history.",
    "commit": null,
    "verification": null
  },
  {
    "area": "surface-kernel",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added export serialization for JSON, CSV, Markdown and plain text with an export manifest, and CSV cell neutralization that prevents a cell from executing as a spreadsheet formula.",
    "commit": null,
    "verification": null
  },
  {
    "area": "surface-kernel",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added per-element appearance overrides bounded by a custom-property allowlist and an inert-value check, with preset export and import.",
    "commit": null,
    "verification": null
  },
  {
    "area": "surface-kernel",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added colour parsing, conversion and formatting across hexadecimal, RGB, HSL, HWB, Lab, LCH, Oklab and Oklch, WCAG 2 contrast ratios and verdicts, and honest out-of-gamut reporting.",
    "commit": null,
    "verification": null
  },
  {
    "area": "surface-kernel",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added presentation locks backed by salted PBKDF2-SHA-256 verifiers with length-constant comparison, together with a constant disclosure sentence stating they are not a security control.",
    "commit": null,
    "verification": null
  },
  {
    "area": "surface-kernel",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added the tab model: ordering, pinning, grouping, dock-aware keyboard movement, overflow, and a bulk close that reports its exact matched set for confirmation.",
    "commit": null,
    "verification": null
  },
  {
    "area": "surface-kernel",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added time-of-day presentation schedules with a documented precedence of manual override over active rule over stored default, and validation of an external presentation-settings document against an https origin allowlist.",
    "commit": null,
    "verification": null
  },
  {
    "area": "surface-kernel",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added a narration queue that keeps exactly one utterance in flight with ordered English-then-Cantonese segments, and a list of field kinds that are never read aloud.",
    "commit": null,
    "verification": null
  },
  {
    "area": "surface-kernel",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added display-name and logo handling, including rejection of vector images and a check of the leading bytes against the declared image type.",
    "commit": null,
    "verification": null
  },
  {
    "area": "surface-kernel",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added a fail-closed conversion registry that returns a named refusal for an unregistered source and target pair.",
    "commit": null,
    "verification": null
  },
  {
    "area": "surface-kernel",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added a documentation parser that produces typed nodes rather than markup, a documentation index with heading outlines and resolved internal links, and documentation search.",
    "commit": null,
    "verification": null
  },
  {
    "area": "surface-kernel",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added changelog parsing and filtering, with commit links produced only from a recorded commit identifier.",
    "commit": null,
    "verification": null
  },
  {
    "area": "surface-kernel",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added an RFC 4226 and RFC 6238 one-time-password utility over Web Cryptography, bound to no account and granting access to nothing, and a dependency-free QR matrix encoder that contacts no external service.",
    "commit": null,
    "verification": null
  },
  {
    "area": "surface-kernel",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added local support tickets whose bodies are redacted before storage or export.",
    "commit": null,
    "verification": null
  },
  {
    "area": "surface-kernel",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added a transfer state machine that cannot reach a complete phase without a measured byte count and that carries `unsigned` as a literal `true`.",
    "commit": null,
    "verification": null
  },
  {
    "area": "surface-kernel",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added the Material 3 token stylesheet with a complete light palette on bare `:root`, a system dark palette guarded against an explicit light choice, and an explicit dark palette, plus the matching token names in TypeScript.",
    "commit": null,
    "verification": null
  },
  {
    "area": "surface-kernel",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added nine `node --test` test files covering the search engine, vocabulary validation, CSV neutralization, append-only history, the RFC 6238 vectors, colour contrast and gamut reporting, schedule precedence, the transfer reducer, and the humour fact invariant.",
    "commit": null,
    "verification": null
  },
  {
    "area": "surface-kernel",
    "version": "Unreleased",
    "date": null,
    "section": "Changed",
    "entry": "Declared the new package as a dependency of the documentation site, the desktop application and the local model package, added build and test scripts to the local model and local coding-assistant packages, and regenerated both `package-lock.json` and `apps/site/package-lock.json` so the manifests and lockfiles agree.",
    "commit": null,
    "verification": null
  },
  {
    "area": "surface-kernel",
    "version": "Unreleased",
    "date": null,
    "section": "Changed",
    "entry": "The documentation site references the two internal packages by relative path, because its lockfile is installed on its own with `npm ci --workspaces=false` and a version range cannot resolve an unpublished package in that mode.",
    "commit": null,
    "verification": null
  },
  {
    "area": "surface-kernel",
    "version": "Unreleased",
    "date": null,
    "section": "Changed",
    "entry": "Split the package entry point by consumer, because a single entry could not serve both. The `.` export is now conditional: bundlers continue to take `default` and read `src/index.ts`, exactly as the documentation site and the desktop renderer bundle always have, while Node takes a new `node` condition and reads a compiled `dist/index.js`. The previous entry offered raw TypeScript to everyone, and Node cannot load a `.ts` file — it strips types only when explicitly asked, and not by default until a release newer than the pinned toolchain — so every file Node executed directly that imported this package by name failed on its first import with `ERR_UNKNOWN_FILE_EXTENSION`. That had already been worked around once in the documentation-site build configuration and was, separately, stopping the desktop application build. A consumer that now reaches the compiled entry before it has been built gets `ERR_MODULE_NOT_FOUND` naming the exact missing file, which says what to do; the error it replaces did not.",
    "commit": null,
    "verification": null
  },
  {
    "area": "surface-kernel",
    "version": "Unreleased",
    "date": null,
    "section": "Changed",
    "entry": "Replaced the package's `build` script, which invoked `tsc` and could never have run: TypeScript is not a declared dependency of this repository or of any workspace in it, and no `tsc` binary is installed. The script now runs a committed build that bundles the source with the same transpiler the desktop application already depends on. It transpiles and does not type-check, deliberately, so the release path depends on a compiler that produces an artifact rather than on a checker that produces a verdict; it pins its own working directory so the artifact is byte-identical wherever it is invoked from; and it asserts that a non-empty file was actually written rather than trusting the transpiler's exit code.",
    "commit": null,
    "verification": null
  },
  {
    "area": "surface-kernel",
    "version": "Unreleased",
    "date": null,
    "section": "Verification",
    "entry": "`tsc -p tsconfig.json` in `packages/surface-kernel`: no diagnostics; a full emit also completed and the generated directory was then removed.",
    "commit": null,
    "verification": null
  },
  {
    "area": "surface-kernel",
    "version": "Unreleased",
    "date": null,
    "section": "Verification",
    "entry": "`node --test --experimental-strip-types test/*.test.ts` in `packages/surface-kernel`: 89 tests, 89 passing, 0 failing.",
    "commit": null,
    "verification": null
  },
  {
    "area": "surface-kernel",
    "version": "Unreleased",
    "date": null,
    "section": "Verification",
    "entry": "`npm install` at the repository root and `npm install --package-lock-only --workspaces=false` in `apps/site`: both completed; `npm ci --prefix . --workspaces=false` in `apps/site` then installed from the regenerated lockfile and linked both workspace packages.",
    "commit": null,
    "verification": null
  },
  {
    "area": "surface-kernel",
    "version": "Unreleased",
    "date": null,
    "section": "Verification",
    "entry": "The QR encoder's format-information and version-information bits were checked against the published tables for error-correction level M, and the non-function module counts for versions 1 to 10 against the published remainder-bit counts; both matched.",
    "commit": null,
    "verification": null
  },
  {
    "area": "surface-kernel",
    "version": "Unreleased",
    "date": null,
    "section": "Verification",
    "entry": "The colour conversions for sRGB red were checked against the published CIE Lab and Oklch values and matched.",
    "commit": null,
    "verification": null
  },
  {
    "area": "tax",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added an explicit 2025 Canada and Ontario annual personal tax domain with guided common-slip, deduction, credit, validation, calculation, carry-forward, import, and redacted export contracts.",
    "commit": null,
    "verification": null
  },
  {
    "area": "tax",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added official 2025 CRA and Ontario source citations and fail-closed handling for unsupported tax years, provinces, and complex tax situations.",
    "commit": null,
    "verification": null
  },
  {
    "area": "tax",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added the CRA mail-in PDF preparation package foundation, official form catalog, and line-to-form mapping.",
    "commit": null,
    "verification": null
  },
  {
    "area": "tax",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Added the mandatory manual-review boundary for every populated form, calculation, attachment, mailing destination, and signature field before export or print.",
    "commit": null,
    "verification": null
  },
  {
    "area": "tax",
    "version": "Unreleased",
    "date": null,
    "section": "Added",
    "entry": "Explicitly prohibited NETFILE, EFILE, electronic submission, direct CRA transmission, simulated filing, and automatic filing.",
    "commit": null,
    "verification": null
  },
  {
    "area": "tax",
    "version": "Unreleased",
    "date": null,
    "section": "Verification",
    "entry": "Tests, lint, type checks, accessibility checks, reviews, captures, browser UI QA, builds, and packaging were not run under the ultra-speed delivery boundary.",
    "commit": null,
    "verification": null
  }
];

export const CHANGELOG_AREAS: string[] = [
  "desktop",
  "docs",
  "local-coding-assistants",
  "ollama",
  "site",
  "slip-parser",
  "surface-kernel",
  "tax"
];

/**
 * The repository this site is published from. `commitUrl` returns null for
 * an entry with no recorded commit identifier, and the viewer then renders no
 * link rather than a guessed address.
 */
export const CHANGELOG_REPOSITORY = "";
